### ISSUE TITLE
Hi everyone, can thie project be setup and run successfully?

### ISSUE THREAD

**Issue by henryhust** [kkjawz/coref-ee#14]
This project seems not to run successfully,  after I see the other issues. Can anybody tell the truth?

**Comment by henryhust** [comment]
yes, it can run successfully. but there missing some files ,you can refer to the 《Higher-order Coreference Resolution with Coarse-to-fine Inference》 to get more information.

**Comment by henryhust** [comment]
It even gets the SOA in my chinese coreference task in special domain.

**Comment by LifeIsStrange** [comment]
After python demo.py final

I get 

Traceback (most recent call last):
  File "demo.py", line 6, in <module>
    import tensorflow as tf
  File "/home/stephane/miniconda3/envs/py36/lib/python3.6/site-packages/tensorflow/__init__.py", line 99, in <module>
    from tensorflow_core import *
  File "/home/stephane/miniconda3/envs/py36/lib/python3.6/site-packages/tensorflow_core/__init__.py", line 28, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
ImportError: cannot import name 'pywrap_tensorflow'

heres my requirements.txt
h5py==2.8.0
nltk==3.4
numpy==1.16
pyhocon==0.3.48
tensorflow-gpu==1.15.2
termcolor==1.1.0
tqdm==4.31.1

with python 3.6

**Comment by LifeIsStrange** [comment]
halp ERROR: astropy 4.0.1.post1 has requirement numpy>=1.16, but you'll have numpy 1.15.0 which is incompatible.

I fail to fix requirements.txt
