### ISSUE TITLE
'extract_bert_features.sh' don't work

### ISSUE THREAD

**Issue by fairy-of-9** [kkjawz/coref-ee#3]
I followed Getting Started.

It's result of `extract_bert_features.sh`
```
Traceback (most recent call last):
  File "extract_features.py", line 342, in <module>
    tf.app.run()
  File "/home/fairy_of_9/anaconda3/envs/bert/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/home/fairy_of_9/anaconda3/envs/bert/lib/python3.6/site-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/home/fairy_of_9/anaconda3/envs/bert/lib/python3.6/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "extract_features.py", line 278, in main
    with open(os.path.join(FLAGS.input_file, x + '.english.jsonlines')) as f:
FileNotFoundError: [Errno 2] No such file or directory: './test.english.jsonlines'

```

I think, `setup_training.sh`  must precede `extract_bert_features.sh`.
Isn't that so?

**Comment by kkjawz** [comment]
You're right, fixed README.
